// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Dionizio8/go-temppc-dist/internal/entity"
	mock "github.com/stretchr/testify/mock"

	trace "go.opentelemetry.io/otel/trace"
)

// MockTemperatureRepository is an autogenerated mock type for the TemperatureRepositoryInterface type
type MockTemperatureRepository struct {
	mock.Mock
}

type MockTemperatureRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemperatureRepository) EXPECT() *MockTemperatureRepository_Expecter {
	return &MockTemperatureRepository_Expecter{mock: &_m.Mock}
}

// GetTemperature provides a mock function with given fields: ctx, city, tracer
func (_m *MockTemperatureRepository) GetTemperature(ctx context.Context, city string, tracer trace.Tracer) (entity.Temperature, error) {
	ret := _m.Called(ctx, city, tracer)

	if len(ret) == 0 {
		panic("no return value specified for GetTemperature")
	}

	var r0 entity.Temperature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, trace.Tracer) (entity.Temperature, error)); ok {
		return rf(ctx, city, tracer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, trace.Tracer) entity.Temperature); ok {
		r0 = rf(ctx, city, tracer)
	} else {
		r0 = ret.Get(0).(entity.Temperature)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, trace.Tracer) error); ok {
		r1 = rf(ctx, city, tracer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemperatureRepository_GetTemperature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemperature'
type MockTemperatureRepository_GetTemperature_Call struct {
	*mock.Call
}

// GetTemperature is a helper method to define mock.On call
//   - ctx context.Context
//   - city string
//   - tracer trace.Tracer
func (_e *MockTemperatureRepository_Expecter) GetTemperature(ctx interface{}, city interface{}, tracer interface{}) *MockTemperatureRepository_GetTemperature_Call {
	return &MockTemperatureRepository_GetTemperature_Call{Call: _e.mock.On("GetTemperature", ctx, city, tracer)}
}

func (_c *MockTemperatureRepository_GetTemperature_Call) Run(run func(ctx context.Context, city string, tracer trace.Tracer)) *MockTemperatureRepository_GetTemperature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(trace.Tracer))
	})
	return _c
}

func (_c *MockTemperatureRepository_GetTemperature_Call) Return(_a0 entity.Temperature, _a1 error) *MockTemperatureRepository_GetTemperature_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemperatureRepository_GetTemperature_Call) RunAndReturn(run func(context.Context, string, trace.Tracer) (entity.Temperature, error)) *MockTemperatureRepository_GetTemperature_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemperatureRepository creates a new instance of MockTemperatureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemperatureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemperatureRepository {
	mock := &MockTemperatureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
