### Service A - validator

###Get Temperatures By validator Ok
POST http://localhost:8080/validator/temperature HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep": "59090050"
}

####

###Get Temperatures 404 By validator [can not find zipcode]
POST http://localhost:8080/validator/temperature HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep": "11111111"
}

####

###Get Temperatures 422 By validator [invalid zipcode]
POST http://localhost:8080/validator/temperature HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep": "124ABC"
}

