### Service A - validator

###Get Temperatures By validator Ok
POST http://localhost:8080/validator/temperature HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep": "59090050"
}

####

###Get Temperatures 404 By validator [can not find zipcode]
POST http://localhost:8080/validator/temperature HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep": "11111111"
}

####

###Get Temperatures 422 By validator [invalid zipcode]
POST http://localhost:8080/validator/temperature HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "cep": "124ABC"
}

### Service B - temppc

###Get Temperatures By temppc Ok
GET http://localhost:8090/temppc/temperature/59090050 HTTP/1.1
Host: localhost:8090
Content-Type: application/json

####

###Get Temperatures 404 By temppc  [can not find zipcode]
GET http://localhost:8090/temppc/temperature/11111111 HTTP/1.1
Host: localhost:8090
Content-Type: application/json

####

###Get Temperatures 422 By temppc  [invalid zipcode]
GET http://localhost:8090/temppc/temperature/124ABC HTTP/1.1
Host: localhost:8090
Content-Type: application/json